version: "3.7"

services:
  caddy:
    container_name: caddy
    build:
      context: caddy/.
    environment:
      ACME_EMAIL: ${ACME_EMAIL}
      DOMAIN_NAME: ${DOMAIN_NAME}
      NAMECHEAP_API_KEY: ${NAMECHEAP_API_KEY}
      NAMECHEAP_USERNAME: ${NAMECHEAP_USERNAME}
      NAMECHEAP_ENDPOINT: ${NAMECHEAP_ENDPOINT}
    ports:
      - "8070:80"
      - "8071:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped
    healthcheck:
      test: curl --fail https://www.${DOMAIN_NAME} || exit 1
    networks:
      - nettop

  fail2ban:
    container_name: fail2ban
    build:
      context: fail2ban/.
    environment:
      F2B_LOG_TARGET: STDOUT
      F2B_LOG_LEVEL: INFO
      F2B_DB_PURGE_AGE: 1d
      SSMTP_HOST: mail.privateemail.com
      SSMTP_PORT: 465
      SSMTP_USER: $F2B_SSMTP_USER
      SSMTP_PASSWORD: $F2B_SSMTP_PASSWORD
      SSMTP_TLS: YES
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - fail2ban-data:/data
      - /var/log:/var/log:ro
    restart: always

  gitlab:
    container_name: gitlab
    build:
      context: gitlab/.
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://gitlab.${DOMAIN_NAME}"
        nginx["listen_port"] = 80
        nginx["listen_https"] = false
        letsencrypt["enable"] = false
        puma["worker_processes"] = 4
        sidekiq["max_concurrency"] = 20
        gitlab_rails["initial_root_password"] = "${GITLAB_ROOT_PASSWORD}"
        registry_external_url "http://registry.${DOMAIN_NAME}"
        registry_nginx["listen_port"] = 5000
        registry_nginx["listen_https"] = false
        grafana["disable_login_form"] = true
        grafana["admin_password"] = "${GITLAB_ROOT_PASSWORD}"
    ports:
      - "4242:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    restart: unless-stopped
    depends_on:
      - caddy
    healthcheck:
      test: curl --fail https://gitlab.${DOMAIN_NAME}/-/readiness || exit 1
      start_period: 5m
    shm_size: "256m"
    networks:
      - nettop

volumes:
  caddy-data:
    external: true
  caddy-config:
  fail2ban-data:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

networks:
  nettop:
    external: true
