version: "3.7"

services:
  fail2ban:
    container_name: fail2ban
    build:
      context: fail2ban/.
    environment:
      SSMTP_HOST: mail.privateemail.com
      SSMTP_PORT: 465
      SSMTP_USER: ${F2B_SSMTP_USER}
      SSMTP_PASSWORD: ${F2B_SSMTP_PASSWORD}
      SSMTP_TLS: "true"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - fail2ban-data:/data
      - /var/log:/var/log:ro
    restart: unless-stopped

  gitlab:
    container_name: gitlab
    build:
      context: gitlab/.
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        letsencrypt["enable"] = true
        letsencrypt["contact_emails"] = ["${ACME_EMAIL}"]
        external_url "https://gitlab.${DOMAIN_NAME}"
        puma["worker_processes"] = 4
        sidekiq["max_concurrency"] = 20
        gitlab_rails["initial_root_password"] = "${GITLAB_ROOT_PASSWORD}"
        gitlab_rails["monitoring_whitelist"] = ["127.0.0.0/8", "192.168.86.0/24"]
        gitlab_rails["backup_path"] = "/mnt/backup"
        registry_external_url "https://registry.${DOMAIN_NAME}"
        grafana["disable_login_form"] = false
        grafana["admin_password"] = "${GITLAB_ROOT_PASSWORD}"
    ports:
      - "2222:22"
      - "8080:80"
      - "8443:443"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8080/-/readiness || exit 1
      start_period: 5m
    shm_size: "256m"

  loki:
    container_name: loki
    image: grafana/loki:2.4.2
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: curl --fail http://localhost:3100/ready || exit 1

  promtail:
    container_name: promtail
    build:
      context: promtail/.
    volumes:
      - /var/log:/var/log:ro
      - gitlab-logs:/gitlab-logs
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.13.1
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: unless-stopped

volumes:
  fail2ban-data:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  portainer-data:
