version: "3.7"

services:
  caddy:
    container_name: caddy
    build:
      context: .
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      NAMECHEAP_API_KEY: ${NAMECHEAP_API_KEY}
      NAMECHEAP_USERNAME: ${NAMECHEAP_USERNAME}
      NAMECHEAP_ENDPOINT: ${NAMECHEAP_ENDPOINT}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./www:/srv
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped
    healthcheck:
      test: curl --fail https://www.${DOMAIN_NAME} || exit 1
    networks:
      - nettop

volumes:
  caddy-data:
    external: true
  caddy-config:

networks:
  nettop:
    external: true
