version: "3.7"

services:
  fail2ban:
    container_name: fail2ban
    build:
      context: .
    image: fail2ban:nettop
    environment:
      F2B_LOG_TARGET: STDOUT
      F2B_LOG_LEVEL: INFO
      F2B_DB_PURGE_AGE: 1d
      # SSMTP_HOST: smtp.example.com
      # SSMTP_PORT: 587
      # SSMTP_HOSTNAME: example.com
      # SSMTP_USER: smtp@example.com
      # SSMTP_PASSWORD:
      # SSMTP_TLS: YES
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - fail2ban-data:/data
      - /var/log:/var/log:ro
    restart: always

volumes:
  fail2ban-data:
